/* Generated by Yosys 0.58+74 (git sha1 272aa9cde, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:1.1-34.10" *)
module PE(clk, reset, clear_acc, v_a_in, v_b_in, a_in, b_in, v_a_out, v_b_out, a_out, b_out, psum);
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:5.32-5.35" *)
  input clk;
  wire clk;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:6.32-6.37" *)
  input reset;
  wire reset;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:7.32-7.41" *)
  input clear_acc;
  wire clear_acc;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:8.32-8.38" *)
  input v_a_in;
  wire v_a_in;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:9.32-9.38" *)
  input v_b_in;
  wire v_b_in;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:10.32-10.36" *)
  input [7:0] a_in;
  wire [7:0] a_in;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:11.32-11.36" *)
  input [7:0] b_in;
  wire [7:0] b_in;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:12.32-12.39" *)
  output v_a_out;
  reg v_a_out;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:13.32-13.39" *)
  output v_b_out;
  reg v_b_out;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:14.32-14.37" *)
  output [7:0] a_out;
  reg [7:0] a_out;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:15.32-15.37" *)
  output [7:0] b_out;
  reg [7:0] b_out;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:16.32-16.36" *)
  output [31:0] psum;
  reg [31:0] psum;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:30.17-30.33" *)
  wire _0000_;
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:19.13-19.31" *)
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  (* unused_bits = "1 2 3 4 5 6 7 8" *)
  wire [31:0] _0481_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11" *)
  wire [31:0] _0482_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire [31:0] _0483_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:200.24-200.25" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [31:0] _0484_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  (* unused_bits = "5 6 7 8 9 10 11 12 13 14 15 16" *)
  wire [31:0] _0485_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _0486_;
  assign _0469_ = a_in[1] & b_in[0];
  assign _0470_ = ~(_0469_ ^ psum[1]);
  assign _0471_ = b_in[1] & a_in[0];
  assign _0472_ = _0471_ ^ _0470_;
  assign _0473_ = b_in[0] & a_in[0];
  assign _0474_ = _0473_ & psum[0];
  assign _0482_[1] = ~(_0474_ ^ _0472_);
  assign _0475_ = a_in[2] & b_in[0];
  assign _0476_ = _0475_ ^ psum[2];
  assign _0477_ = ~(b_in[1] & a_in[1]);
  assign _0478_ = _0477_ ^ _0476_;
  assign _0479_ = ~(_0469_ & psum[1]);
  assign _0480_ = _0471_ & ~(_0470_);
  assign _0002_ = _0479_ & ~(_0480_);
  assign _0003_ = ~(_0002_ ^ _0478_);
  assign _0004_ = b_in[2] & a_in[0];
  assign _0005_ = _0004_ ^ _0003_;
  assign _0006_ = _0474_ & ~(_0472_);
  assign _0483_[2] = ~(_0006_ ^ _0005_);
  assign _0007_ = a_in[3] & b_in[0];
  assign _0008_ = _0007_ ^ psum[3];
  assign _0009_ = ~(b_in[1] & a_in[2]);
  assign _0010_ = _0009_ ^ _0008_;
  assign _0011_ = ~(_0475_ & psum[2]);
  assign _0012_ = _0476_ & ~(_0477_);
  assign _0013_ = _0011_ & ~(_0012_);
  assign _0014_ = _0013_ ^ _0010_;
  assign _0015_ = b_in[2] & a_in[1];
  assign _0016_ = b_in[3] & a_in[0];
  assign _0017_ = ~(_0016_ ^ _0015_);
  assign _0018_ = _0017_ ^ _0014_;
  assign _0019_ = ~_0018_;
  assign _0020_ = _0002_ | _0478_;
  assign _0021_ = _0004_ & ~(_0003_);
  assign _0022_ = _0020_ & ~(_0021_);
  assign _0023_ = _0022_ ^ _0019_;
  assign _0024_ = _0006_ & ~(_0005_);
  assign _0484_[3] = ~(_0024_ ^ _0023_);
  assign _0025_ = a_in[5] & b_in[0];
  assign _0026_ = _0025_ ^ psum[5];
  assign _0027_ = ~(b_in[1] & a_in[4]);
  assign _0028_ = _0027_ ^ _0026_;
  assign _0029_ = a_in[4] & b_in[0];
  assign _0030_ = ~(_0029_ & psum[4]);
  assign _0031_ = b_in[1] & a_in[3];
  assign _0032_ = ~(_0029_ ^ psum[4]);
  assign _0033_ = _0031_ & ~(_0032_);
  assign _0034_ = _0030_ & ~(_0033_);
  assign _0035_ = _0034_ ^ _0028_;
  assign _0036_ = b_in[2] & a_in[3];
  assign _0037_ = b_in[3] & a_in[2];
  assign _0038_ = _0037_ ^ _0036_;
  assign _0039_ = ~(b_in[4] & a_in[1]);
  assign _0040_ = _0039_ ^ _0038_;
  assign _0041_ = _0040_ ^ _0035_;
  assign _0042_ = ~(_0032_ ^ _0031_);
  assign _0043_ = ~(_0007_ & psum[3]);
  assign _0044_ = _0008_ & ~(_0009_);
  assign _0045_ = _0043_ & ~(_0044_);
  assign _0046_ = _0045_ | ~(_0042_);
  assign _0047_ = b_in[2] & a_in[2];
  assign _0048_ = b_in[3] & a_in[1];
  assign _0049_ = _0048_ ^ _0047_;
  assign _0050_ = b_in[4] & a_in[0];
  assign _0051_ = _0050_ ^ _0049_;
  assign _0052_ = _0045_ ^ _0042_;
  assign _0053_ = _0051_ & ~(_0052_);
  assign _0054_ = _0046_ & ~(_0053_);
  assign _0055_ = _0054_ ^ _0041_;
  assign _0056_ = _0048_ & _0047_;
  assign _0057_ = _0050_ & _0049_;
  assign _0058_ = ~(_0057_ | _0056_);
  assign _0059_ = b_in[5] & a_in[0];
  assign _0060_ = _0059_ ^ _0058_;
  assign _0061_ = _0060_ ^ _0055_;
  assign _0062_ = ~(_0052_ ^ _0051_);
  assign _0063_ = _0013_ | _0010_;
  assign _0064_ = _0014_ & ~(_0017_);
  assign _0065_ = _0063_ & ~(_0064_);
  assign _0066_ = _0065_ | ~(_0062_);
  assign _0067_ = _0016_ & _0015_;
  assign _0068_ = _0065_ ^ _0062_;
  assign _0069_ = _0067_ & ~(_0068_);
  assign _0070_ = _0066_ & ~(_0069_);
  assign _0071_ = _0070_ ^ _0061_;
  assign _0072_ = ~(_0068_ ^ _0067_);
  assign _0073_ = _0019_ & ~(_0022_);
  assign _0074_ = ~_0073_;
  assign _0075_ = _0072_ & ~(_0074_);
  assign _0076_ = _0075_ ^ _0071_;
  assign _0077_ = _0074_ ^ _0072_;
  assign _0078_ = _0024_ & ~(_0023_);
  assign _0079_ = ~_0078_;
  assign _0080_ = _0079_ | _0077_;
  assign _0486_[5] = ~(_0080_ ^ _0076_);
  assign _0081_ = a_in[6] & b_in[0];
  assign _0082_ = _0081_ ^ psum[6];
  assign _0083_ = ~(b_in[1] & a_in[5]);
  assign _0084_ = _0083_ ^ _0082_;
  assign _0085_ = ~(_0025_ & psum[5]);
  assign _0086_ = _0026_ & ~(_0027_);
  assign _0087_ = _0085_ & ~(_0086_);
  assign _0088_ = _0087_ ^ _0084_;
  assign _0089_ = ~(b_in[2] & a_in[4]);
  assign _0090_ = ~(b_in[3] & a_in[3]);
  assign _0091_ = _0090_ ^ _0089_;
  assign _0092_ = ~(b_in[4] & a_in[2]);
  assign _0093_ = _0092_ ^ _0091_;
  assign _0094_ = _0093_ ^ _0088_;
  assign _0095_ = _0034_ | _0028_;
  assign _0096_ = _0035_ & ~(_0040_);
  assign _0097_ = _0095_ & ~(_0096_);
  assign _0098_ = _0097_ ^ _0094_;
  assign _0099_ = _0037_ & _0036_;
  assign _0100_ = _0038_ & ~(_0039_);
  assign _0101_ = _0100_ | _0099_;
  assign _0102_ = b_in[5] & a_in[1];
  assign _0103_ = b_in[6] & a_in[0];
  assign _0104_ = ~(_0103_ ^ _0102_);
  assign _0105_ = _0104_ ^ _0101_;
  assign _0106_ = _0105_ ^ _0098_;
  assign _0107_ = _0054_ | _0041_;
  assign _0108_ = _0055_ & ~(_0060_);
  assign _0109_ = _0107_ & ~(_0108_);
  assign _0110_ = _0109_ ^ _0106_;
  assign _0111_ = _0059_ & ~(_0058_);
  assign _0112_ = ~_0111_;
  assign _0113_ = _0112_ ^ _0110_;
  assign _0114_ = _0070_ | _0061_;
  assign _0115_ = ~(_0114_ ^ _0113_);
  assign _0116_ = _0075_ & _0071_;
  assign _0117_ = _0076_ & ~(_0080_);
  assign _0118_ = _0117_ | _0116_;
  assign _0486_[6] = ~(_0118_ ^ _0115_);
  assign _0119_ = a_in[7] & b_in[0];
  assign _0120_ = _0119_ ^ psum[7];
  assign _0121_ = ~(b_in[1] & a_in[6]);
  assign _0122_ = _0121_ ^ _0120_;
  assign _0123_ = ~(_0081_ & psum[6]);
  assign _0124_ = _0082_ & ~(_0083_);
  assign _0125_ = _0123_ & ~(_0124_);
  assign _0126_ = _0125_ ^ _0122_;
  assign _0127_ = ~(b_in[2] & a_in[5]);
  assign _0128_ = ~(b_in[3] & a_in[4]);
  assign _0129_ = _0128_ ^ _0127_;
  assign _0130_ = ~(b_in[4] & a_in[3]);
  assign _0131_ = _0130_ ^ _0129_;
  assign _0132_ = _0131_ ^ _0126_;
  assign _0133_ = _0087_ | _0084_;
  assign _0134_ = _0088_ & ~(_0093_);
  assign _0135_ = _0133_ & ~(_0134_);
  assign _0136_ = _0135_ ^ _0132_;
  assign _0137_ = _0090_ | _0089_;
  assign _0138_ = _0091_ & ~(_0092_);
  assign _0139_ = _0137_ & ~(_0138_);
  assign _0140_ = ~(b_in[5] & a_in[2]);
  assign _0141_ = b_in[6] & a_in[1];
  assign _0142_ = ~(_0141_ ^ _0140_);
  assign _0143_ = b_in[7] & a_in[0];
  assign _0144_ = ~_0143_;
  assign _0145_ = _0144_ ^ _0142_;
  assign _0146_ = _0145_ ^ _0139_;
  assign _0147_ = _0103_ & _0102_;
  assign _0148_ = ~_0147_;
  assign _0149_ = _0148_ ^ _0146_;
  assign _0150_ = _0149_ ^ _0136_;
  assign _0151_ = _0097_ | _0094_;
  assign _0152_ = _0098_ & ~(_0105_);
  assign _0153_ = _0151_ & ~(_0152_);
  assign _0154_ = _0153_ ^ _0150_;
  assign _0155_ = _0101_ & ~(_0104_);
  assign _0156_ = _0155_ ^ _0154_;
  assign _0157_ = _0109_ | _0106_;
  assign _0158_ = _0110_ & ~(_0112_);
  assign _0159_ = _0157_ & ~(_0158_);
  assign _0160_ = _0159_ ^ _0156_;
  assign _0161_ = _0114_ | _0113_;
  assign _0162_ = _0118_ & ~(_0115_);
  assign _0163_ = _0161_ & ~(_0162_);
  assign _0486_[7] = _0163_ ^ _0160_;
  assign _0164_ = b_in[1] & a_in[7];
  assign _0165_ = ~(_0164_ ^ psum[8]);
  assign _0166_ = ~(_0119_ & psum[7]);
  assign _0167_ = _0120_ & ~(_0121_);
  assign _0168_ = _0166_ & ~(_0167_);
  assign _0169_ = _0168_ ^ _0165_;
  assign _0170_ = ~(b_in[2] & a_in[6]);
  assign _0171_ = ~(b_in[3] & a_in[5]);
  assign _0172_ = _0171_ ^ _0170_;
  assign _0173_ = ~(b_in[4] & a_in[4]);
  assign _0174_ = _0173_ ^ _0172_;
  assign _0175_ = _0174_ ^ _0169_;
  assign _0176_ = _0125_ | _0122_;
  assign _0177_ = _0126_ & ~(_0131_);
  assign _0178_ = _0176_ & ~(_0177_);
  assign _0179_ = _0178_ ^ _0175_;
  assign _0180_ = _0128_ | _0127_;
  assign _0181_ = _0129_ & ~(_0130_);
  assign _0182_ = _0180_ & ~(_0181_);
  assign _0183_ = ~(b_in[5] & a_in[3]);
  assign _0184_ = b_in[6] & a_in[2];
  assign _0185_ = ~(_0184_ ^ _0183_);
  assign _0186_ = b_in[7] & a_in[1];
  assign _0187_ = ~_0186_;
  assign _0188_ = _0187_ ^ _0185_;
  assign _0189_ = _0188_ ^ _0182_;
  assign _0190_ = _0140_ | ~(_0141_);
  assign _0191_ = _0142_ & ~(_0144_);
  assign _0192_ = _0190_ & ~(_0191_);
  assign _0193_ = _0192_ ^ _0189_;
  assign _0194_ = _0193_ ^ _0179_;
  assign _0195_ = _0135_ | _0132_;
  assign _0196_ = _0136_ & ~(_0149_);
  assign _0197_ = _0195_ & ~(_0196_);
  assign _0198_ = _0197_ ^ _0194_;
  assign _0199_ = _0145_ | _0139_;
  assign _0200_ = _0146_ & ~(_0148_);
  assign _0201_ = _0199_ & ~(_0200_);
  assign _0202_ = _0201_ ^ _0198_;
  assign _0203_ = _0153_ | _0150_;
  assign _0204_ = _0155_ & _0154_;
  assign _0205_ = _0203_ & ~(_0204_);
  assign _0206_ = ~(_0205_ ^ _0202_);
  assign _0207_ = _0156_ & ~(_0159_);
  assign _0208_ = ~(_0161_ | _0160_);
  assign _0209_ = _0208_ | _0207_;
  assign _0210_ = _0160_ | _0115_;
  assign _0211_ = _0118_ & ~(_0210_);
  assign _0212_ = _0211_ | _0209_;
  assign _0486_[8] = ~(_0212_ ^ _0206_);
  assign _0213_ = _0164_ & psum[8];
  assign _0214_ = _0213_ ^ psum[9];
  assign _0215_ = ~(b_in[2] & a_in[7]);
  assign _0216_ = ~(b_in[3] & a_in[6]);
  assign _0217_ = _0216_ ^ _0215_;
  assign _0218_ = ~(b_in[4] & a_in[5]);
  assign _0219_ = _0218_ ^ _0217_;
  assign _0220_ = _0219_ ^ _0214_;
  assign _0221_ = _0168_ | _0165_;
  assign _0222_ = _0169_ & ~(_0174_);
  assign _0223_ = _0221_ & ~(_0222_);
  assign _0224_ = _0223_ ^ _0220_;
  assign _0225_ = _0171_ | _0170_;
  assign _0226_ = _0172_ & ~(_0173_);
  assign _0227_ = _0225_ & ~(_0226_);
  assign _0228_ = ~(b_in[5] & a_in[4]);
  assign _0229_ = b_in[6] & a_in[3];
  assign _0230_ = ~(_0229_ ^ _0228_);
  assign _0231_ = b_in[7] & a_in[2];
  assign _0232_ = ~_0231_;
  assign _0233_ = _0232_ ^ _0230_;
  assign _0234_ = _0233_ ^ _0227_;
  assign _0235_ = _0183_ | ~(_0184_);
  assign _0236_ = _0185_ & ~(_0187_);
  assign _0237_ = _0235_ & ~(_0236_);
  assign _0238_ = _0237_ ^ _0234_;
  assign _0239_ = _0238_ ^ _0224_;
  assign _0240_ = _0178_ | _0175_;
  assign _0241_ = _0179_ & ~(_0193_);
  assign _0242_ = _0240_ & ~(_0241_);
  assign _0243_ = _0242_ ^ _0239_;
  assign _0244_ = _0188_ | _0182_;
  assign _0245_ = _0189_ & ~(_0192_);
  assign _0246_ = _0244_ & ~(_0245_);
  assign _0247_ = ~(_0246_ ^ _0243_);
  assign _0248_ = _0197_ | _0194_;
  assign _0249_ = _0198_ & ~(_0201_);
  assign _0250_ = _0248_ & ~(_0249_);
  assign _0251_ = _0250_ ^ _0247_;
  assign _0252_ = _0205_ | _0202_;
  assign _0253_ = _0212_ & ~(_0206_);
  assign _0254_ = _0252_ & ~(_0253_);
  assign _0486_[9] = _0254_ ^ _0251_;
  assign _0255_ = ~(b_in[3] & a_in[7]);
  assign _0256_ = b_in[4] & a_in[6];
  assign _0257_ = _0256_ ^ _0255_;
  assign _0258_ = _0257_ ^ psum[10];
  assign _0259_ = ~(_0213_ & psum[9]);
  assign _0260_ = _0214_ & ~(_0219_);
  assign _0261_ = _0259_ & ~(_0260_);
  assign _0262_ = _0261_ ^ _0258_;
  assign _0263_ = _0216_ | _0215_;
  assign _0264_ = _0217_ & ~(_0218_);
  assign _0265_ = _0263_ & ~(_0264_);
  assign _0266_ = ~(b_in[5] & a_in[5]);
  assign _0267_ = b_in[6] & a_in[4];
  assign _0268_ = ~(_0267_ ^ _0266_);
  assign _0269_ = b_in[7] & a_in[3];
  assign _0270_ = ~_0269_;
  assign _0271_ = _0270_ ^ _0268_;
  assign _0272_ = _0271_ ^ _0265_;
  assign _0273_ = _0228_ | ~(_0229_);
  assign _0274_ = _0230_ & ~(_0232_);
  assign _0275_ = _0273_ & ~(_0274_);
  assign _0276_ = _0275_ ^ _0272_;
  assign _0277_ = _0276_ ^ _0262_;
  assign _0278_ = _0223_ | _0220_;
  assign _0279_ = _0224_ & ~(_0238_);
  assign _0280_ = _0278_ & ~(_0279_);
  assign _0281_ = _0280_ ^ _0277_;
  assign _0282_ = _0233_ | _0227_;
  assign _0283_ = _0234_ & ~(_0237_);
  assign _0284_ = _0282_ & ~(_0283_);
  assign _0285_ = _0284_ ^ _0281_;
  assign _0286_ = _0242_ | _0239_;
  assign _0287_ = _0243_ & ~(_0246_);
  assign _0288_ = _0286_ & ~(_0287_);
  assign _0289_ = ~(_0288_ ^ _0285_);
  assign _0290_ = _0247_ & ~(_0250_);
  assign _0291_ = ~(_0252_ | _0251_);
  assign _0292_ = _0291_ | _0290_;
  assign _0293_ = _0251_ | _0206_;
  assign _0294_ = _0293_ | ~(_0212_);
  assign _0295_ = _0294_ & ~(_0292_);
  assign _0486_[10] = _0295_ ^ _0289_;
  assign _0296_ = ~psum[11];
  assign _0297_ = b_in[4] & a_in[7];
  assign _0298_ = _0297_ ^ _0296_;
  assign _0299_ = psum[10] & ~(_0257_);
  assign _0300_ = _0299_ ^ _0298_;
  assign _0301_ = ~_0300_;
  assign _0302_ = _0255_ | ~(_0256_);
  assign _0303_ = ~(b_in[5] & a_in[6]);
  assign _0304_ = b_in[6] & a_in[5];
  assign _0305_ = _0304_ ^ _0303_;
  assign _0306_ = b_in[7] & a_in[4];
  assign _0307_ = _0306_ ^ _0305_;
  assign _0308_ = _0307_ ^ _0302_;
  assign _0309_ = _0266_ | ~(_0267_);
  assign _0310_ = _0268_ & ~(_0270_);
  assign _0311_ = _0309_ & ~(_0310_);
  assign _0312_ = _0311_ ^ _0308_;
  assign _0313_ = _0312_ ^ _0301_;
  assign _0314_ = _0261_ | _0258_;
  assign _0315_ = _0262_ & ~(_0276_);
  assign _0316_ = _0314_ & ~(_0315_);
  assign _0317_ = _0316_ ^ _0313_;
  assign _0318_ = _0271_ | _0265_;
  assign _0319_ = _0272_ & ~(_0275_);
  assign _0320_ = _0318_ & ~(_0319_);
  assign _0321_ = ~(_0320_ ^ _0317_);
  assign _0322_ = _0280_ | _0277_;
  assign _0323_ = _0281_ & ~(_0284_);
  assign _0324_ = _0322_ & ~(_0323_);
  assign _0325_ = _0324_ ^ _0321_;
  assign _0326_ = _0288_ | _0285_;
  assign _0327_ = ~(_0295_ | _0289_);
  assign _0328_ = _0326_ & ~(_0327_);
  assign _0486_[11] = _0328_ ^ _0325_;
  assign _0329_ = _0297_ & ~(_0296_);
  assign _0330_ = ~(_0329_ ^ psum[12]);
  assign _0331_ = ~_0330_;
  assign _0332_ = b_in[5] & a_in[7];
  assign _0333_ = b_in[6] & a_in[6];
  assign _0334_ = ~(_0333_ ^ _0332_);
  assign _0335_ = b_in[7] & a_in[5];
  assign _0336_ = _0335_ ^ _0334_;
  assign _0337_ = ~_0336_;
  assign _0338_ = _0303_ | ~(_0304_);
  assign _0339_ = _0306_ & ~(_0305_);
  assign _0340_ = _0338_ & ~(_0339_);
  assign _0341_ = _0340_ ^ _0337_;
  assign _0342_ = _0341_ ^ _0331_;
  assign _0343_ = _0298_ | ~(_0299_);
  assign _0344_ = _0301_ & ~(_0312_);
  assign _0345_ = _0343_ & ~(_0344_);
  assign _0346_ = _0345_ ^ _0342_;
  assign _0347_ = _0307_ | _0302_;
  assign _0348_ = _0308_ & ~(_0311_);
  assign _0349_ = _0347_ & ~(_0348_);
  assign _0350_ = _0349_ ^ _0346_;
  assign _0351_ = _0316_ | _0313_;
  assign _0352_ = _0317_ & ~(_0320_);
  assign _0353_ = _0351_ & ~(_0352_);
  assign _0354_ = ~(_0353_ ^ _0350_);
  assign _0355_ = _0321_ & ~(_0324_);
  assign _0356_ = ~(_0326_ | _0325_);
  assign _0357_ = _0356_ | _0355_;
  assign _0358_ = _0325_ | _0289_;
  assign _0359_ = _0292_ & ~(_0358_);
  assign _0360_ = _0359_ | _0357_;
  assign _0361_ = _0358_ | _0293_;
  assign _0362_ = _0212_ & ~(_0361_);
  assign _0363_ = ~(_0362_ | _0360_);
  assign _0486_[12] = _0363_ ^ _0354_;
  assign _0364_ = b_in[6] & a_in[7];
  assign _0365_ = b_in[7] & a_in[6];
  assign _0366_ = ~(_0365_ ^ _0364_);
  assign _0367_ = ~_0366_;
  assign _0368_ = ~(_0333_ & _0332_);
  assign _0369_ = _0335_ & ~(_0334_);
  assign _0370_ = _0368_ & ~(_0369_);
  assign _0371_ = _0370_ ^ _0367_;
  assign _0372_ = _0371_ ^ psum[13];
  assign _0373_ = ~(_0329_ & psum[12]);
  assign _0374_ = _0331_ & ~(_0341_);
  assign _0375_ = _0373_ & ~(_0374_);
  assign _0376_ = ~(_0375_ ^ _0372_);
  assign _0377_ = _0337_ & ~(_0340_);
  assign _0378_ = _0377_ ^ _0376_;
  assign _0379_ = _0345_ | _0342_;
  assign _0380_ = _0346_ & ~(_0349_);
  assign _0381_ = _0379_ & ~(_0380_);
  assign _0382_ = _0381_ ^ _0378_;
  assign _0383_ = ~_0382_;
  assign _0384_ = _0353_ | _0350_;
  assign _0385_ = ~(_0363_ | _0354_);
  assign _0386_ = _0384_ & ~(_0385_);
  assign _0486_[13] = _0386_ ^ _0383_;
  assign _0387_ = b_in[7] & a_in[7];
  assign _0388_ = ~_0387_;
  assign _0389_ = _0365_ & _0364_;
  assign _0390_ = _0389_ ^ _0388_;
  assign _0391_ = _0390_ ^ psum[14];
  assign _0392_ = psum[13] & ~(_0371_);
  assign _0393_ = _0392_ ^ _0391_;
  assign _0394_ = _0367_ & ~(_0370_);
  assign _0395_ = _0394_ ^ _0393_;
  assign _0396_ = _0375_ | _0372_;
  assign _0397_ = _0377_ & ~(_0376_);
  assign _0398_ = _0396_ & ~(_0397_);
  assign _0399_ = ~(_0398_ ^ _0395_);
  assign _0400_ = ~(_0381_ | _0378_);
  assign _0401_ = _0382_ & ~(_0384_);
  assign _0402_ = _0401_ | _0400_;
  assign _0403_ = _0383_ | _0354_;
  assign _0404_ = _0403_ | _0363_;
  assign _0405_ = _0404_ & ~(_0402_);
  assign _0486_[14] = _0405_ ^ _0399_;
  assign _0406_ = psum[14] & ~(_0390_);
  assign _0407_ = ~(_0406_ ^ psum[15]);
  assign _0408_ = _0389_ & ~(_0388_);
  assign _0409_ = _0408_ ^ _0407_;
  assign _0410_ = ~_0409_;
  assign _0411_ = _0391_ | ~(_0392_);
  assign _0412_ = _0394_ & ~(_0393_);
  assign _0413_ = _0411_ & ~(_0412_);
  assign _0414_ = _0413_ ^ _0410_;
  assign _0415_ = _0398_ | _0395_;
  assign _0416_ = ~(_0405_ | _0399_);
  assign _0417_ = _0415_ & ~(_0416_);
  assign _0486_[15] = _0417_ ^ _0414_;
  assign _0418_ = ~(_0406_ & psum[15]);
  assign _0419_ = _0408_ & ~(_0407_);
  assign _0420_ = _0418_ & ~(_0419_);
  assign _0421_ = _0420_ ^ psum[16];
  assign _0422_ = _0410_ & ~(_0413_);
  assign _0423_ = ~(_0415_ | _0414_);
  assign _0424_ = _0423_ | _0422_;
  assign _0425_ = _0414_ | _0399_;
  assign _0426_ = _0402_ & ~(_0425_);
  assign _0427_ = _0426_ | _0424_;
  assign _0428_ = _0425_ | _0403_;
  assign _0429_ = _0360_ & ~(_0428_);
  assign _0430_ = _0429_ | _0427_;
  assign _0431_ = _0428_ | _0361_;
  assign _0432_ = _0212_ & ~(_0431_);
  assign _0433_ = _0432_ | _0430_;
  assign _0486_[16] = ~(_0433_ ^ _0421_);
  assign _0434_ = ~psum[17];
  assign _0435_ = _0420_ | ~(psum[16]);
  assign _0436_ = _0433_ & ~(_0421_);
  assign _0437_ = _0435_ & ~(_0436_);
  assign _0486_[17] = _0437_ ^ _0434_;
  assign _0438_ = _0435_ | _0434_;
  assign _0439_ = _0421_ | _0434_;
  assign _0440_ = _0433_ & ~(_0439_);
  assign _0441_ = _0438_ & ~(_0440_);
  assign _0486_[18] = ~(_0441_ ^ psum[18]);
  assign _0442_ = psum[18] & ~(_0441_);
  assign _0486_[19] = _0442_ ^ psum[19];
  assign _0443_ = ~(psum[19] & psum[18]);
  assign _0444_ = _0443_ | _0438_;
  assign _0445_ = _0443_ | _0439_;
  assign _0446_ = _0433_ & ~(_0445_);
  assign _0447_ = _0444_ & ~(_0446_);
  assign _0486_[20] = ~(_0447_ ^ psum[20]);
  assign _0448_ = psum[20] & ~(_0447_);
  assign _0486_[21] = _0448_ ^ psum[21];
  assign _0449_ = ~(psum[21] & psum[20]);
  assign _0450_ = _0449_ | _0447_;
  assign _0486_[22] = ~(_0450_ ^ psum[22]);
  assign _0451_ = psum[22] & ~(_0450_);
  assign _0486_[23] = _0451_ ^ psum[23];
  assign _0452_ = ~(psum[23] & psum[22]);
  assign _0453_ = _0452_ | _0449_;
  assign _0454_ = _0453_ | _0444_;
  assign _0455_ = _0453_ | _0445_;
  assign _0456_ = _0433_ & ~(_0455_);
  assign _0457_ = _0454_ & ~(_0456_);
  assign _0486_[24] = ~(_0457_ ^ psum[24]);
  assign _0458_ = psum[24] & ~(_0457_);
  assign _0486_[25] = _0458_ ^ psum[25];
  assign _0459_ = ~(psum[25] & psum[24]);
  assign _0460_ = _0459_ | _0457_;
  assign _0486_[26] = ~(_0460_ ^ psum[26]);
  assign _0461_ = psum[26] & ~(_0460_);
  assign _0486_[27] = _0461_ ^ psum[27];
  assign _0462_ = ~(psum[27] & psum[26]);
  assign _0463_ = _0462_ | _0459_;
  assign _0464_ = _0463_ | _0457_;
  assign _0486_[28] = ~(_0464_ ^ psum[28]);
  assign _0465_ = psum[28] & ~(_0464_);
  assign _0486_[29] = _0465_ ^ psum[29];
  assign _0466_ = ~(psum[29] & psum[28]);
  assign _0467_ = _0466_ | _0464_;
  assign _0486_[30] = ~(_0467_ ^ psum[30]);
  assign _0468_ = psum[30] & ~(_0467_);
  assign _0486_[31] = _0468_ ^ psum[31];
  assign _0485_[4] = _0079_ ^ _0077_;
  assign _0481_[0] = _0473_ ^ psum[0];
  assign _0001_ = clear_acc | reset;
  assign _0000_ = v_b_in & v_a_in;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) v_a_out <= 1'h0;
    else v_a_out <= v_a_in;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) v_b_out <= 1'h0;
    else v_b_out <= v_b_in;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) a_out[0] <= 1'h0;
    else a_out[0] <= a_in[0];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) a_out[1] <= 1'h0;
    else a_out[1] <= a_in[1];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) a_out[2] <= 1'h0;
    else a_out[2] <= a_in[2];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) a_out[3] <= 1'h0;
    else a_out[3] <= a_in[3];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) a_out[4] <= 1'h0;
    else a_out[4] <= a_in[4];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) a_out[5] <= 1'h0;
    else a_out[5] <= a_in[5];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) a_out[6] <= 1'h0;
    else a_out[6] <= a_in[6];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) a_out[7] <= 1'h0;
    else a_out[7] <= a_in[7];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) b_out[0] <= 1'h0;
    else b_out[0] <= b_in[0];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) b_out[1] <= 1'h0;
    else b_out[1] <= b_in[1];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) b_out[2] <= 1'h0;
    else b_out[2] <= b_in[2];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) b_out[3] <= 1'h0;
    else b_out[3] <= b_in[3];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) b_out[4] <= 1'h0;
    else b_out[4] <= b_in[4];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) b_out[5] <= 1'h0;
    else b_out[5] <= b_in[5];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) b_out[6] <= 1'h0;
    else b_out[6] <= b_in[6];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) b_out[7] <= 1'h0;
    else b_out[7] <= b_in[7];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[0] <= 1'h0;
    else if (_0000_) psum[0] <= _0481_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[1] <= 1'h0;
    else if (_0000_) psum[1] <= _0482_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[2] <= 1'h0;
    else if (_0000_) psum[2] <= _0483_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[3] <= 1'h0;
    else if (_0000_) psum[3] <= _0484_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[4] <= 1'h0;
    else if (_0000_) psum[4] <= _0485_[4];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[5] <= 1'h0;
    else if (_0000_) psum[5] <= _0486_[5];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[6] <= 1'h0;
    else if (_0000_) psum[6] <= _0486_[6];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[7] <= 1'h0;
    else if (_0000_) psum[7] <= _0486_[7];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[8] <= 1'h0;
    else if (_0000_) psum[8] <= _0486_[8];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[9] <= 1'h0;
    else if (_0000_) psum[9] <= _0486_[9];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[10] <= 1'h0;
    else if (_0000_) psum[10] <= _0486_[10];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[11] <= 1'h0;
    else if (_0000_) psum[11] <= _0486_[11];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[12] <= 1'h0;
    else if (_0000_) psum[12] <= _0486_[12];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[13] <= 1'h0;
    else if (_0000_) psum[13] <= _0486_[13];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[14] <= 1'h0;
    else if (_0000_) psum[14] <= _0486_[14];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[15] <= 1'h0;
    else if (_0000_) psum[15] <= _0486_[15];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[16] <= 1'h0;
    else if (_0000_) psum[16] <= _0486_[16];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[17] <= 1'h0;
    else if (_0000_) psum[17] <= _0486_[17];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[18] <= 1'h0;
    else if (_0000_) psum[18] <= _0486_[18];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[19] <= 1'h0;
    else if (_0000_) psum[19] <= _0486_[19];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[20] <= 1'h0;
    else if (_0000_) psum[20] <= _0486_[20];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[21] <= 1'h0;
    else if (_0000_) psum[21] <= _0486_[21];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[22] <= 1'h0;
    else if (_0000_) psum[22] <= _0486_[22];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[23] <= 1'h0;
    else if (_0000_) psum[23] <= _0486_[23];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[24] <= 1'h0;
    else if (_0000_) psum[24] <= _0486_[24];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[25] <= 1'h0;
    else if (_0000_) psum[25] <= _0486_[25];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[26] <= 1'h0;
    else if (_0000_) psum[26] <= _0486_[26];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[27] <= 1'h0;
    else if (_0000_) psum[27] <= _0486_[27];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[28] <= 1'h0;
    else if (_0000_) psum[28] <= _0486_[28];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[29] <= 1'h0;
    else if (_0000_) psum[29] <= _0486_[29];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[30] <= 1'h0;
    else if (_0000_) psum[30] <= _0486_[30];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/anils_0611/vlsi_projects/pe_asic/rtl/PE.sv:18.5-33.8" *)
  always @(posedge clk)
    if (_0001_) psum[31] <= 1'h0;
    else if (_0000_) psum[31] <= _0486_[31];
  assign _0481_[31:9] = psum[31:9];
  assign { _0482_[31:12], _0482_[0] } = { psum[31:12], _0481_[0] };
  assign { _0483_[31:15], _0483_[1:0] } = { psum[31:15], _0482_[1], _0481_[0] };
  assign { _0484_[31:16], _0484_[2:0] } = { psum[31:16], _0483_[2], _0482_[1], _0481_[0] };
  assign { _0485_[31:17], _0485_[3:0] } = { psum[31:17], _0484_[3], _0483_[2], _0482_[1], _0481_[0] };
  assign _0486_[4:0] = { _0485_[4], _0484_[3], _0483_[2], _0482_[1], _0481_[0] };
endmodule
