// Auto-generated by OpenLane
module PE(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  input clear_acc,
  input v_a_in,
  input v_b_in,
  input[7:0] a_in,
  input[7:0] b_in,
  output v_a_out,
  output v_b_out,
  output[7:0] a_out,
  output[7:0] b_out,
  output[31:0] psum
);
endmodule
